sudo: required
services:
  - docker

before_install:
  - docker build -t istruthy/docker-react -f Dockerfile.dev .

script:
  - docker run istruthy/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-270144690558"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESSKEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  
   